name: CI

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-18.04

    steps:
    - uses: actions/checkout@v1

    - name: Environment variables
      run: env

    - name: Disable xdebug
      run: |
        xdebug_ini=$(php -i | grep -i "xdebug.ini" | sed -e 's/,$//')
        sudo sed -Ei 's/^(zend_extension=.*)/; \1/' $xdebug_ini
        cat $xdebug_ini
        php -v

    - name: list files
      run: |
        echo "Where am I?"
        pwd
        echo "Files in the current folder:"
        ls -hal --color
        
    - name: Composer
      run: composer --version

    - name: MySQL
      run: mysql -uroot -proot -e "SHOW VARIABLES LIKE \"%version%\";"

    - name: Node environement
      run: |
        node --version
        which yarn
        node -e "console.log(process);"

