name: CI

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-18.04
    services:
      mysql:
        image: mysql:5.7
        env:
          MYSQL_ROOT_PASSWORD: root
        ports: [3306]

    steps:
    - uses: actions/checkout@v1
    - name: list files
      run: |
        pwd
        ls -hal --color
        which php
        which composer
        php --version
        composer --version
        env
        which mysql
        mysql -v -uroot -proot
