name: CI

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-18.04

    steps:
    - uses: actions/checkout@v1

    - name: Disable xdebug
      run: |
        xdebug_ini=$(php -i | grep -i "xdebug.ini" | sed -e 's/,$//')
        echo $xdebug_ini
        cat $xdebug_ini

    - name: list files
      run: |
        pwd
        ls -hal --color
        composer --version
        env
        which mysql
        mysql -uroot -proot -e "SHOW VARIABLES LIKE \"%version%\";"
