name: CI

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-18.04

    steps:
    - uses: actions/checkout@v1

    - name: Disable xdebug
      run: |
        xdebug_ini=$(php -i | grep -i \"xdebug.ini\" | sed -E \'s/,$//\')
        sed -E 's/^(zend_extension=.*)/; \1/' < $xdebug_ini | tee $xdebug_ini
        cat /etc/php/7.3/cli/conf.d/20-xdebug.ini
        php --version

    - name: list files
      run: |
        pwd
        ls -hal --color
        composer --version
        env
        which mysql
        mysql -uroot -proot -e "SHOW VARIABLES LIKE \"%version%\";"
