name: CI

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-18.04

    steps:
    - uses: actions/checkout@v1
    - name: list files
      run: |
        pwd
        ls -hal --color
        phpenv config-rm xdebug.ini || true
        php --version
        composer --version
        env
        which mysql
        mysql -uroot -proot -e "SHOW VARIABLES LIKE \"%version%\";"
