name: CI

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-18.04

    steps:
    - uses: actions/checkout@v1
    - name: list files
      run: |
        pwd
        ls -hal --color
        cat /etc/php/7.3/cli/conf.d/20-xdebug.ini
        php --version
        composer --version
        env
        which mysql
        mysql -uroot -proot -e "SHOW VARIABLES LIKE \"%version%\";"
